### ISSUE TITLE
Battery Indicator - Hower

### ISSUE THREAD

**Issue by muskan-setiya** [Git-For-Geeks/Webdev-mini-projects#7]
- Hower to battery tile
![Battery-1](https://user-images.githubusercontent.com/78153457/195632337-e87118ce-cf69-4776-b827-1a04dba6da7e.png)

**Comment by Mrugal4** [comment]
Hi @muskan-setiya 
What type of hover effect is expected in the battery indicator ?

**Comment by Kush-munot** [comment]
@Mrugal4 when you hover on the card the background must become dark for light mode and light background for dark mode.
